name: Build Windows Binary

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Package to Windows .exe
        run: npx @yao-pkg/pkg index.js --targets node20-win-x64 --output dist/omomodular.exe

      - name: Upload Windows Binary
        uses: actions/upload-artifact@v4
        with:
          name: omomodular-windows
          path: dist/omomodular.exe
